import Cookies from "js-cookie";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";
import AccesoDenegado from "../../components/Admin/AccesoDenegado";
import MiniDrawer from "../../components/Admin/MiniDrawer";
import WithAdminRoute from "../../components/Auth/WithAdminRoute";
import { loggin, logginAdmin, loggoutAdmin } from "../../context/actions";
import useAppContext from "../../context/Store";

const Admin = () => {
  const router = useRouter();
  const { value } = useAppContext();
  const { state, dispatch } = value;
  const { adminLogged } = state;

  useEffect(() => {
   
      let user = localStorage.getItem("user");
      if (user.rol === 1) {
        dispatch(logginAdmin(user));
      } else {
        dispatch(loggin(user));
      }
      // TODO MANTENER LA SESION DE EL ADMINISTRADOR
    
  }, [dispatch]);
  
  if (!adminLogged) {
    return <AccesoDenegado />;
  }

  return (
    <>
      <Head>
        <title>Luz Mar - Administrador</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
        <MiniDrawer >

        <p>Administrados Screen</p>
        </MiniDrawer>
      
    </>
  );
};

export default Admin;

Admin.Auth = WithAdminRoute;
