import Cookies from "js-cookie";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import AccesoDenegado from "../../components/Admin/AccesoDenegado";
import MiniDrawer from "../../components/Admin/MiniDrawer";
import WithAdminRoute from "../../components/Auth/WithAdminRoute";
import { loggin, logginAdmin, loggoutAdmin, logout } from "../../context/actions";
import useAppContext from "../../context/Store";

const Admin = () => {
  const router = useRouter();
  const { value } = useAppContext();
  const { state, dispatch } = value;
  const { adminLogged } = state;
  const [userLog, setuserLog] = useState(null)

 useEffect(() => {
   if (localStorage.getItem("token")) {
     fetch(`${process.env.NEXT_PUBLIC_API}/api/auth/comprobarToken`, {
       method: "POST",
       headers: {
         "Content-Type": "application/json",
       },
       body: JSON.stringify({ token: localStorage.getItem("token") }),
     })
       .then((res) => res.json())
       .then((resp) => {
         console.log(resp);
         if (resp.expirado) {
           dispatch(logout());
           localStorage.clear();

         } else {
           localStorage.setItem(
             "user",
             JSON.stringify({
               id: resp[0].idUsuario,
               correo: resp[0].correo,
               nombre: resp[0].nombre,
               direccion: resp[0].direccion,
               rol: resp[0].rol,
               domicilio: null,
               avatar: resp[0].avatar,
             })
           );
           if (resp[0].rol === 1) {
             dispatch(
               logginAdmin({
                 id: resp[0].idUsuario,
                 correo: resp[0].correo,
                 nombre: resp[0].nombre,
                 direccion: resp[0].direccion,
                 rol: resp[0].rol,
                 domicilio: null,
                 avatar: resp[0].avatar,
               })
             );
             router.push("/admin");
           } else {
             dispatch(
               loggin({
                 id: resp[0].idUsuario,
                 correo: resp[0].correo,
                 nombre: resp[0].nombre,
                 direccion: resp[0].direccion,
                 rol: resp[0].rol,
                 domicilio: null,
                 avatar: resp[0].avatar,
               })
             );
           }
         }
       });
     // TODO MANTENER LA SESION DE EL ADMINISTRADOR
   }
 }, []);

  
  
  // if (!adminLogged || localStorage.getItem("user")?.rol == 2) {
  //   return <AccesoDenegado />;
  // }
  

  return (
    <>
      <Head>
        <title>Luz Mar - Administrador</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
        <MiniDrawer >

        <p>Administrados Screen</p>
        </MiniDrawer>
      
    </>
  );
};

export default Admin;

Admin.Auth = WithAdminRoute;
