import Head from "next/head";
import Link from 'next/link'
import Image from "next/image";
import {useAlert} from 'react-alert'

import ProductoScreen from "../components/global/ProductoScreen";
import ProductoDomicilio from "../components/tudomicilio/ProductoDomicilio";
import { TituloProducto } from "../components/tudomicilio/productoStyles";
import Publicidad from "../components/index/publicidad/Publicidad";
import SectionFamilia from "../components/index/familia/SectionFamilia";
import useAppContext from "../context/Store";
import {  cartDelete, decrementProduct, incrementProduct } from "../context/actions";

export default function Domicilio() {
  const alert = useAlert()
  const { value } = useAppContext()
  const { state , dispatch } = value;
  const { cart } = state

   const deleteP = (props)=> {
     dispatch(cartDelete(props));
     alert.show("Producto eliminado del carrito");
  }
   const incrementProd = (id)=> {
    dispatch(incrementProduct(id));
    //  alert.success("Producto agregado al carrito");
  }
  const decrementProd = (id)=> {
    dispatch(decrementProduct(id))
  }
  
  return (
    <>
      <Head>
        <title>Luz Mar - Droguerias</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TituloProducto>Tus Productos </TituloProducto>
      <div style={{ display: "flex", flexWrap: "wrap" }}>
        {cart.cartItems.length === 0 ? (
          <h1> No hay productos en su domicilio </h1>
        ) : (
          cart.cartItems.map((item) => (
            <ProductoDomicilio
              key={item.id}
              deleteP={deleteP}
              add={incrementProd}
              decrement={decrementProd}
              widthCel="370px"
              heightCel="150px"
              widthImg="120px"
              widthPc="400px"
              heightPc="220px"
              marginleft={true}
              counter={true}
              {...item}
            />
          ))
        )}

       
      </div>
      <Publicidad />
      <SectionFamilia />
    </>
  );
}
