import Head from "next/head";
import Link from 'next/link'
import Image from "next/image";


import ProductoScreen from "../components/global/ProductoScreen";
import ProductoDomicilio from "../components/tudomicilio/ProductoDomicilio";
import { TituloProducto } from "../components/tudomicilio/productoStyles";
import Publicidad from "../components/index/publicidad/Publicidad";
import SectionFamilia from "../components/index/familia/SectionFamilia";

export default function Domicilio() {
  return (
    <>
      <Head>
        <title>Luz Mar - Droguerias</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TituloProducto>Tus Productos </TituloProducto>
      <div style={{ display: "flex", flexWrap: "wrap" }}>
        <ProductoDomicilio
          widthCel="370px"
          heightCel="150px"
          widthImg="120px"
          widthPc="400px"
          heightPc="220px"
          marginleft={true}
          counter={true}
        />
        <ProductoDomicilio
          widthCel="370px"
          heightCel="150px"
          widthImg="120px"
          widthPc="400px"
          heightPc="220px"
          marginleft={true}
          counter={true}
        />
        <ProductoDomicilio
          widthCel="370px"
          heightCel="150px"
          widthImg="120px"
          widthPc="400px"
          heightPc="220px"
          marginleft={true}
          counter={true}
        />
        <ProductoDomicilio
          widthCel="370px"
          heightCel="150px"
          widthImg="120px"
          widthPc="400px"
          heightPc="220px"
          marginleft={true}
          counter={true}
        />
      </div>
      <Publicidad/>
      <SectionFamilia/>
    </>
  );
}
