import Head from "next/head";
import Link from 'next/link'
import Image from "next/image";

import "rc-rate/assets/index.css";
import ProductoScreen from "../components/global/ProductoScreen";

export default function Domicilio() {
  return (
    <>
      <Head>
        <title>Luz Mar - Droguerias</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href="/producto/campera"> Producto </Link>
    </>
  );
}
