import Head from 'next/head'
import Image from 'next/image'
import Buscador from '../components/index/buscador/Buscador'
import Carousel from '../components/index/carousel/Carousel'
import CarouselBanner from '../components/index/carousel/CarouselBanner'
import Producto from '../components/index/carouselProductos/Producto'
import Publicidad from '../components/index/publicidad/Publicidad'
import styles from '../styles/Home.module.css'


export default function Home() {
  return (
    <div
      style={{
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
      }}
    >
      <Head>
        <title>Luz Mar - Droguerias</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Buscador />
      <Carousel
        pcSlide={1}
        banner={true}
        dots={true}
        onBanner={() => <CarouselBanner />}
      />
      <Publicidad />
      <h1 className="title_home">Super Descuentos</h1>
      <Carousel
        color="#EF1837"
        pcSlide={4}
        dots={false}
        dctos={true}
        onDctos={() => <Producto />}
      />
      <h1 className="title_home">Ofertas</h1>
      <Carousel
        color="#EF1837"
        pcSlide={4}
        dots={false}
        offer={true}
        onOffer={() => <Producto />}
      />
    </div>
  );
}
