import Head from 'next/head'
import Image from 'next/image'
import Buscador from '../components/index/buscador/Buscador'
import Carousel from '../components/index/carousel/Carousel'
import CarouselBanner from '../components/index/carousel/CarouselBanner'
import styles from '../styles/Home.module.css'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Luz Mar - Droguerias</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <Buscador/>
     <Carousel
      slide={1}
      banner={true}
      dots={true}
      onBanner={()=> <CarouselBanner/>}
     />
     
    </div>
  )
}
