import Head from "next/head";
import Image from "next/image";
import SectionFamilia from "../components/index/familia/SectionFamilia";
import QuienesSomosSection from "../components/quienesSomos/QuienesSomosSection";
import styles from "../styles/Home.module.css";

export default function QuienesSomos() {
  return (
    <>
      <Head>
        <title>Luz Mar - Droguerias</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <QuienesSomosSection />
      <h1 className="title_home">Familia Luz Mar</h1>
      <SectionFamilia />
    </>
  );
}
